version: "3.9"
services:
    web:
        build: .
        environment:
            - DatabaseServer=mssqlserver
            - DatabaseName=rwm
            - DatabaseUser=sa
            - DatabaseUserPassword=danu@123
        ports:
            - "8000:80"
        depends_on:
            - mssqlserver
    mssqlserver:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1445:1433"
        environment:
            SA_PASSWORD: "danu@123"
            ACCEPT_EULA: "Y"